apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: demo-vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-secret
  data:
  - secretKey: DB_USER
    remoteRef:
      key: demo
      property: DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: demo
      property: DB_PASSWORD
  - secretKey: DB_HOST
    remoteRef:
      key: demo
      property: DB_HOST
  - secretKey: DB_NAME
    remoteRef:
      key: demo
      property: DB_NAME
