apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: demo-vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-secret
  data:
  - secretKey: RABBITMQ_PASSWORD
    remoteRef:
      key: demo
      property: RABBITMQ_PASSWORD
  - secretKey: RABBITMQ_USER
    remoteRef:
      key: demo
      property: RABBITMQ_USER
